### PR TITLE
Grammar and flow updates to reflected XSS findings

### PR DESCRIPTION
**Pull request by RRudder**
Updated the grammar and flow of the reflected XSS subset of XSS findings, including adding in a recommendations heading

### CODE REVIEW

**Comment by drunkrhin0** [comment]
For the first couple I'd recommend @vortexau or someone who's primarily involved in templates to look at this :)

**Comment by vortexau** [comment]
I'm questioning the value of recommendations being present in the templates themselves as this is something researchers will likely delete entirely in many cases.

I'd also like to call out `x-xss-protection: 1; mode=block ` being present as a recommendation, as it is on the way to be deprecated with Safari being the only modern browser that honors the header.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by RRudder** [comment]
Thanks for the feedback, I'll add that to my notes and update the recommendations accordingly. 

I've removed the recommendations from the templates, just leaving in the grammar and flow changes

**Comment by vortexau** [comment]
Right, gotcha, I missed that they'd been removed - I hate reading PRs sometimes 🤦 
Will review the changes.

**Review by vortexau — APPROVED** [review]
Definate improvement in the wording used; nice work!

**Comment by RRudder** [comment]
Thanks mate!

And all good! It was my second PR so I'm not that great at them yet :D

**Comment by RRudder** [comment]
Closing this PR as other PRs have more up to date edits to findings. Please see #61 (Stored XSS findings) or #62 (Reflected XSS findings).

**Pull request closed without merging**
